# Generated by Django 5.0.4 on 2024-05-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=250)),
                ('mota', models.TextField(blank=True, null=True)),
                ('gia', models.FloatField()),
                ('gioitinh', models.CharField(default='unisex', max_length=10)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('kichhoat', models.BooleanField(default=True)),
                ('hinhanh', models.ImageField(default='avatar.jpg', upload_to='profile_avatars')),
                ('danhmuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.danhmuc')),
            ],
        ),
    ]
