# Generated by Django 5.0.4 on 2024-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sanpham'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='gioitinh',
            field=models.CharField(choices=[('Nam', 'Nam'), ('Nu', 'Nữ'), ('Unisex', 'Unisex')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='hinhanh',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
