# Generated by Django 5.0.4 on 2024-05-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sanpham_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='gia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
