# Generated by Django 5.0.4 on 2024-05-08 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sanpham_gia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mausac', models.CharField(max_length=55)),
                ('hinhanh', models.ImageField(upload_to='uploads')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='KichCoSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kichco', models.CharField(max_length=55)),
                ('soluong', models.IntegerField(default=1)),
                ('loaisanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.loaisanpham')),
            ],
        ),
    ]
