# Generated by Django 5.0.4 on 2024-05-10 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_diachi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhuongThucThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThaiDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trangthai', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.FloatField(blank=True)),
                ('soluong', models.IntegerField(blank=True)),
                ('kichcosanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kichcosanpham')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGiaSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sosao', models.IntegerField()),
                ('binhluan', models.TextField(blank=True)),
                ('chitietdonhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chitietdonhang')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tongtien', models.FloatField(blank=True, null=True)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaysua', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phuongthucthanhtoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phuongthucthanhtoan')),
                ('trangthaidonhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trangthaidonhang')),
            ],
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='donhang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donhang'),
        ),
        migrations.CreateModel(
            name='ThongTinDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoten', models.CharField(max_length=100)),
                ('sdt', models.CharField(max_length=12)),
                ('diachinhanhang', models.TextField(blank=True)),
                ('donhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.donhang')),
            ],
        ),
    ]
